apiVersion: v1
kind: ConfigMap
metadata:
  name: template-cron-job-ingress-override-cm
  namespace:  devtroncd
data:
  override: |
#    apiVersion: extensions/v1beta1  #For k8s < 1.19
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata: 
      name: template-cron-job-ingress
#    update:
#      metadata:
#        annotations:
#          owner: app1
#      spec:
#        rules:
#        - http:
#            host: http://change-me
