version = 1

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_paths = ["github.com/devtron-labs/template-cron-job"]
  import_root = " github.com/devtron-labs/template-cron-job"

[[transformers]]
name = "gofmt"
enabled = true
