{{- if $.Values.components }}
{{- if $.Values.components.template-cron-job }}
{{- if $.Values.components.template-cron-job.ingress }}
{{- if $.Values.components.template-cron-job.ingress.enabled }}
{{- with $.Values.components.template-cron-job.ingress }}
{{- if eq $.Values.configs.ENABLE_LEGACY_API "true" }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: template-cron-job
    release: template-cron-job
  name: template-cron-job-ingress
  annotations:
    kubernetes.io/ingress.class: {{ .className }}
    {{- if .annotations }}
{{ toYaml .annotations | nindent 4 }}
    {{- end }}
spec:
  rules:
  - host: {{ .host }}
    http:
      paths:
      - backend:
          serviceName: template-cron-job-service
          servicePort: 80
        path: /orchestrator
      - backend:
          serviceName: template-cron-job-service
          servicePort: 80
        path: /dashboard
      - backend:
          serviceName: template-cron-job-service
          servicePort: 80
        path: /grafana
        pathType: ImplementationSpecific
  {{- if .tls }}
  tls:
{{ toYaml .tls | nindent 4 }}
  {{- end }}
{{- else }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: template-cron-job
    release: template-cron-job
    {{- if .labels }}
    {{ toYaml .labels | nindent 4 }}
    {{- end }}
  name: template-cron-job-ingress
  {{- if .annotations }}
  annotations:
{{ toYaml .annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if .className }}
  ingressClassName: {{ .className }}
  {{- end }}
  rules:
  - host: {{ .host }}
    http:
      paths:
      - backend:
          service:
            name: template-cron-job-service
            port:
              number: 80
        path: /orchestrator
        pathType: {{ .pathType }}
      - backend:
          service:
            name: template-cron-job-service
            port:
              number: 80
        path: /dashboard
        pathType: {{ .pathType }}
      - backend:
          service:
            name: template-cron-job-service
            port:
              number: 80
        path: /grafana
        pathType: {{ .pathType }}
  {{- if .tls }}
  tls:
{{ toYaml .tls | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
