{{- with .Values.components.template-cron-job }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "template-cron-job-cm"
  labels:
    release: template-cron-job
  annotations:
    "helm.sh/resource-policy": keep
data:
  PG_USER: postgres
  PG_ADDR: postgresql-postgresql.devtroncd
  PG_PORT: "5432"
  HELM_CLIENT_URL: kubelink-service:50051
  DASHBOARD_PORT: "80"
  DASHBOARD_HOST: dashboard-service.devtroncd
  PG_DATABASE: orchestrator
  DEX_HOST: http://argocd-dex-server.devtroncd
  DEX_PORT: "5556"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-cron-job
  labels:
    app: template-cron-job
    release: template-cron-job
  annotations:
    "helm.sh/resource-policy": keep
spec:
  selector:
    matchLabels:
      app: template-cron-job
      release: template-cron-job
  replicas: 1
  {{- if $.Release.IsUpgrade }}
  minReadySeconds: 700
  progressDeadlineSeconds: 800
  {{- else }}
  minReadySeconds: 60
  {{- end }}
  template:
    metadata:
      labels:
        app: template-cron-job
        release: template-cron-job
    spec:
      terminationGracePeriodSeconds: 30
      restartPolicy: Always
      serviceAccountName: template-cron-job
      containers:
        - name: template-cron-job
          {{- if $.Values.installer.modules }}
          {{ range $.Values.installer.modules }}
          {{- if and (eq . "cicd") ($.Release.IsUpgrade) }}
          image: {{ $.Values.components.template-cron-job.cicdImage }}
          {{- else }}
          image: {{ $.Values.components.template-cron-job.image }}
          {{- end }}
          {{- end }}
          {{- else }}
          image: {{ $.Values.components.template-cron-job.image }}
          {{- end }}
          imagePullPolicy: {{ .imagePullPolicy }}
          ports:
            - name: template-cron-job
              containerPort: 8080
              protocol: TCP
          env:
            - name: DEVTRON_APP_NAME
              value: template-cron-job
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          envFrom:
          - configMapRef:
              name: "template-cron-job-cm"
          - secretRef:
              name: "template-cron-job-secret"
  revisionHistoryLimit: 3
---
{{- if .serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: template-cron-job-sm
  labels:
    kind: Prometheus
    app: template-cron-job
    release: template-cron-job
  annotations:
    "helm.sh/resource-policy": keep
spec:
  endpoints:
    - port: template-cron-job
      path: /metrics
      scheme: http
      interval: 30s
      scrapeTimeout: 3s
  selector:
    matchLabels:
      app: template-cron-job
{{- end }}
{{- end }}
