{{- with .Values.components.migrator }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: postgresql-migrate-template-cron-job-{{ randAlphaNum 5 | lower }}
  annotations: {}
  labels:
    job: postgresql-migrate-template-cron-job
spec:
  ttlSecondsAfterFinished: 1000
  template:
    spec:
      containers:
      - name: postgresql-migrate-template-cron-job
        image: {{ .image }}
        env:
        - name: GIT_BRANCH
          value: {{ .envVars.template-cron-job.GIT_BRANCH }}
        - name: SCRIPT_LOCATION
          value: {{ .envVars.template-cron-job.SCRIPT_LOCATION }}
        - name: GIT_REPO_URL
          value: {{ .envVars.template-cron-job.GIT_REPO_URL }}
        - name: DB_TYPE
          value: postgres
        - name: DB_USER_NAME
          value: postgres
        - name: DB_HOST
          value: postgresql-postgresql.devtroncd
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: {{ .envVars.template-cron-job.DB_NAME }}
        - name: MIGRATE_TO_VERSION
          value: "0"
        - name: GIT_HASH
          value: {{ .envVars.template-cron-job.GIT_HASH }}
        envFrom:
          - secretRef:
              name: postgresql-migrator
      restartPolicy: OnFailure
  backoffLimit: 20
  activeDeadlineSeconds: 1500
---
apiVersion: batch/v1
kind: Job
metadata:
  name: postgresql-migrate-casbin-{{ randAlphaNum 5 | lower }}
  annotations: {}
spec:
  template:
    spec:
      serviceAccountName: template-cron-job
      containers:
      - name: template-cron-job-rollout
        image: "quay.io/template-cron-job/kubectl:latest"
        command: ['sh', '-c', 'kubectl rollout restart deployment/template-cron-job -n devtroncd']
      initContainers:
      - name: postgresql-migrate-casbin
        image: {{ .image }}
        env:
        - name: SCRIPT_LOCATION
          value: {{ .envVars.casbin.SCRIPT_LOCATION }}
        - name: GIT_REPO_URL
          value: {{ .envVars.casbin.GIT_REPO_URL }}
        - name: DB_TYPE
          value: postgres
        - name: DB_USER_NAME
          value: postgres
        - name: DB_HOST
          value: postgresql-postgresql.devtroncd
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: {{ .envVars.casbin.DB_NAME }}
        - name: MIGRATE_TO_VERSION
          value: "0"
        - name: GIT_HASH
          value: {{ .envVars.casbin.GIT_HASH }}
        - name: GIT_BRANCH
          value: {{ .envVars.casbin.GIT_BRANCH }}
        envFrom:
          - secretRef:
              name: postgresql-migrator
        resources:
          requests:
            cpu: 0.5
            memory: 500Mi
      restartPolicy: OnFailure
  backoffLimit: 20
  activeDeadlineSeconds: 1500
{{- end }}
